import type { PromptPack } from './prompts';

// Built-in themed packs, seeded into the prompt file the first time it's read
// after an upgrade. Once saved they're ordinary packs the admin can edit.

export const BUILT_IN_PACKS: PromptPack[] = [
  {
    id: 'family',
    name: 'Family Friendly',
    emoji: '👨‍👩‍👧',
    quipClash: [
      'The worst thing to find in your lunchbox',
      'A terrible name for a pet goldfish',
      'What the family dog does when nobody is home',
      'The worst chore ever invented',
      'A bad flavor for a birthday cake',
      'What grandma is secretly great at',
      'The worst superhero sidekick',
      'A rejected name for a theme park ride',
      'The silliest rule a school could make',
      'What the tooth fairy does with all those teeth',
      'The worst thing to bring to show and tell',
      'A new holiday everyone should celebrate',
    ],
    theFaker: [
      'Pretend to brush your teeth',
      'Flap your arms like a chicken',
      'Pretend to eat an ice cream cone',
      'Wave like you just saw a friend',
      'Pretend to ride a bicycle',
      'Act like you are very sleepy',
      'Pretend to throw a snowball',
      'Hop on one foot',
    ],
    bracketBattles: [
      'The best pizza topping',
      'The best thing to do on a snow day',
      'The coolest animal',
      'The best dessert',
      'The best board game',
      'The best cartoon character',
      'The best thing about summer',
      'The best breakfast food',
      'The funniest sound',
      'The best superpower for a kid',
    ],
    triviaQuestions: [
      { question: 'How many legs does a spider have?', choices: ['6', '8', '10', '12'], answer: 1, category: 'Animals' },
      { question: 'What color do you get by mixing blue and yellow?', choices: ['Purple', 'Orange', 'Green', 'Brown'], answer: 2, category: 'Art' },
      { question: 'Which planet is known as the Red Planet?', choices: ['Venus', 'Mars', 'Jupiter', 'Saturn'], answer: 1, category: 'Space' },
      { question: 'What do bees make?', choices: ['Milk', 'Silk', 'Honey', 'Wax only'], answer: 2, category: 'Animals' },
      { question: 'How many days are in a leap year?', choices: ['364', '365', '366', '367'], answer: 2, category: 'Calendar' },
      { question: 'What is the largest ocean on Earth?', choices: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 3, category: 'Geography' },
    ],
  },
  {
    id: 'office',
    name: 'Office Life',
    emoji: '💼',
    quipClash: [
      'The worst thing to say in a job interview',
      'A terrible name for a startup',
      'What really happens in the meeting that could have been an email',
      'The worst reply-all email',
      'A new corporate buzzword that should never exist',
      'The worst team-building activity',
      'What the office printer is plotting',
      'A terrible out-of-office message',
      'The worst thing to microwave in the break room',
      'A rejected company motto',
      'What your boss does all day, really',
      'The worst perk a company could offer',
    ],
    theFaker: [
      'Pretend to type very fast',
      'Act like you are on a video call with a bad connection',
      'Pretend to drink coffee that is too hot',
      'Give a thumbs up like you agree in a meeting',
      'Pretend to fix a paper jam',
      'Act like you just remembered a deadline',
      'Pretend to hand someone a business card',
      'Stretch like you have been at your desk all day',
    ],
    bracketBattles: [
      'The best excuse for being late',
      'The best office snack',
      'The best day of the week',
      'The best thing to do on a lunch break',
      'The most useful office supply',
      'The best meeting that never happened',
      'The best job title',
      'The best way to end a workday',
      'The best office prank',
      'The best reason to leave a meeting early',
    ],
    triviaQuestions: [
      { question: 'What does "CC" stand for in email?', choices: ['Carbon copy', 'Copy chain', 'Central contact', 'Closed circle'], answer: 0, category: 'Office' },
      { question: 'Which company makes the Excel spreadsheet?', choices: ['Apple', 'Google', 'Microsoft', 'Oracle'], answer: 2, category: 'Tech' },
      { question: 'What does "ASAP" stand for?', choices: ['As soon as possible', 'All staff at play', 'Always send a proposal', 'Ask someone and proceed'], answer: 0, category: 'Office' },
      { question: 'In which year did the first iPhone come out?', choices: ['2005', '2007', '2009', '2011'], answer: 1, category: 'Tech' },
      { question: 'What is a "KPI"?', choices: ['Key performance indicator', 'Known process issue', 'Keyboard pointer input', 'Key partner invoice'], answer: 0, category: 'Business' },
      { question: 'How many hours are in a standard work week in the US?', choices: ['35', '40', '45', '50'], answer: 1, category: 'Office' },
    ],
  },
  {
    id: 'geek',
    name: 'Geek Out',
    emoji: '🤓',
    quipClash: [
      'The worst name for a programming language',
      'What the robots will do first when they take over',
      'A terrible feature for a video game',
      'The real reason the Wi-Fi is slow',
      'A rejected Star Wars droid',
      'The worst error message a computer could show',
      'What is actually inside a black hole',
      'A terrible name for a spaceship',
      'The worst thing to 3D print',
      'What your smart speaker says when you are not home',
      'A terrible password hint',
      'The worst app to exist',
    ],
    theFaker: [
      'Pretend to swing a lightsaber',
      'Act like you are playing a video game controller',
      'Pretend to cast a magic spell',
      'Do the robot for a second',
      'Pretend to look through a telescope',
      'Act like you are solving a Rubik\'s cube',
      'Pretend to put on a VR headset',
      'Type on an invisible keyboard',
    ],
    bracketBattles: [
      'The best sci-fi movie',
      'The best video game console',
      'The best superpower',
      'The best fictional spaceship',
      'The best board game for game night',
      'The best planet to visit',
      'The best robot in pop culture',
      'The best way to spend a rainy weekend',
      'The best programming language (fight me)',
      'The best fantasy creature',
    ],
    triviaQuestions: [
      { question: 'What does "HTTP" stand for?', choices: ['HyperText Transfer Protocol', 'High Traffic Transfer Process', 'Host Text Transport Protocol', 'Hyper Terminal Test Program'], answer: 0, category: 'Tech' },
      { question: 'Which planet has the most moons (as of 2024)?', choices: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 1, category: 'Space' },
      { question: 'What is the binary number 1010 in decimal?', choices: ['8', '10', '12', '5'], answer: 1, category: 'Math' },
      { question: 'Who wrote "The Hitchhiker\'s Guide to the Galaxy"?', choices: ['Isaac Asimov', 'Douglas Adams', 'Arthur C. Clarke', 'Terry Pratchett'], answer: 1, category: 'Books' },
      { question: 'What is the chemical symbol for gold?', choices: ['Go', 'Gd', 'Au', 'Ag'], answer: 2, category: 'Science' },
      { question: 'Which company created the Raspberry Pi?', choices: ['Arduino', 'Raspberry Pi Foundation', 'Intel', 'Adafruit'], answer: 1, category: 'Tech' },
    ],
  },
];
