// Letterboxd Top 500 Films – based on community weighted ratings
// Source: letterboxd.com official list (as of early 2026)
export const LETTERBOXD_TOP_500: string[] = [
  // Top 50
  "Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles",
  "Mulholland Drive",
  "2001: A Space Odyssey",
  "Vertigo",
  "Chungking Express",
  "In the Mood for Love",
  "Stalker",
  "Beau Travail",
  "Persona",
  "Singin' in the Rain",
  "Mirror",
  "Apocalypse Now",
  "8½",
  "Ordet",
  "Tokyo Story",
  "A Brighter Summer Day",
  "Andrei Rublev",
  "Cleo from 5 to 7",
  "Bicycle Thieves",
  "Satantango",
  "Sunrise: A Song of Two Humans",
  "The Tree of Life",
  "The Godfather",
  "City Lights",
  "La Dolce Vita",
  "The Night of the Hunter",
  "Pather Panchali",
  "Sansho the Bailiff",
  "Playtime",
  "L'Avventura",
  "The Pianist",
  "Schindler's List",
  "Barry Lyndon",
  "Certified Copy",
  "Come and See",
  "Pickpocket",
  "Au Hasard Balthazar",
  "Rashomon",
  "All About Eve",
  "Contempt",
  "A Man Escaped",
  "Nostalghia",
  "Nashville",
  "Chinatown",
  "The Conversation",
  "Network",
  "Suspiria",
  "Fitzcarraldo",
  "Days of Heaven",
  "The Passenger",
  // 51-100
  "The Discreet Charm of the Bourgeoisie",
  "Viridiana",
  "The Battle of Algiers",
  "The Rules of the Game",
  "Three Colors: Blue",
  "Lost in Translation",
  "A Separation",
  "Three Colors: Red",
  "Blade Runner",
  "Magnolia",
  "There Will Be Blood",
  "No Country for Old Men",
  "Roma",
  "Parasite",
  "The Turin Horse",
  "Uncle Boonmee Who Can Recall His Past Lives",
  "Still Walking",
  "Yi Yi",
  "After Life",
  "L'Eclisse",
  "Aguirre, the Wrath of God",
  "The Color of Pomegranates",
  "F for Fake",
  "Rocco and His Brothers",
  "Solaris",
  "Badlands",
  "Breathless",
  "Le Mépris",
  "Masculin Féminin",
  "Written on the Wind",
  "Imitation of Life",
  "All That Heaven Allows",
  "The Magnificent Ambersons",
  "Citizen Kane",
  "The Searchers",
  "Rio Bravo",
  "The Good, the Bad and the Ugly",
  "Once Upon a Time in the West",
  "Safe",
  "Far from Heaven",
  "I'm Not There",
  "Velvet Goldmine",
  "Adaptation",
  "Happy Together",
  "Fallen Angels",
  "Days of Being Wild",
  "Flowers of Shanghai",
  "A City of Sadness",
  "The Terrorizers",
  "Yi Yi",
  // 101-150
  "Millennium Mambo",
  "The Puppetmaster",
  "What Time Is It There?",
  "Vive L'Amour",
  "The River",
  "Tropical Malady",
  "Blissfully Yours",
  "Syndromes and a Century",
  "Uncle Boonmee",
  "Cemetery of Splendour",
  "Memoria",
  "Mekong Hotel",
  "Taste of Cherry",
  "Close-Up",
  "A Separation",
  "The Wind Will Carry Us",
  "The White Balloon",
  "Ten",
  "Through the Olive Trees",
  "Where Is the Friend's Home?",
  "The Gleaners and I",
  "Vagabond",
  "Le Bonheur",
  "Cléo de 5 à 7",
  "One Sings the Other Doesn't",
  "The Passion of Joan of Arc",
  "Vampyr",
  "Gertrud",
  "Day of Wrath",
  "Ordet",
  "Ivan the Terrible Part I",
  "Man with a Movie Camera",
  "Battleship Potemkin",
  "Strike",
  "Mother",
  "Earth",
  "Diary of a Country Priest",
  "A Gentle Woman",
  "Four Nights of a Dreamer",
  "Lancelot du Lac",
  "The Devil Probably",
  "L'Argent",
  "Caché",
  "The White Ribbon",
  "Amour",
  "The Piano Teacher",
  "Funny Games",
  "Code Unknown",
  "71 Fragments of a Chronology of Chance",
  "The Seventh Continent",
  // 151-200
  "Benny's Video",
  "Ali: Fear Eats the Soul",
  "The Bitter Tears of Petra von Kant",
  "The Marriage of Maria Braun",
  "Veronika Voss",
  "Fox and His Friends",
  "In a Year of 13 Moons",
  "Berlin Alexanderplatz",
  "Wings of Desire",
  "Kings of the Road",
  "Alice in the Cities",
  "Paris, Texas",
  "The American Friend",
  "The State of Things",
  "Stroszek",
  "Woyzeck",
  "Heart of Glass",
  "The Enigma of Kaspar Hauser",
  "Nosferatu the Vampyre",
  "Grizzly Man",
  "Cave of Forgotten Dreams",
  "Pierrot le Fou",
  "Band of Outsiders",
  "Weekend",
  "2 or 3 Things I Know About Her",
  "Alphaville",
  "La Jetée",
  "Sans Soleil",
  "The Last Metro",
  "Jules and Jim",
  "The 400 Blows",
  "Wild Strawberries",
  "The Seventh Seal",
  "Scenes from a Marriage",
  "Autumn Sonata",
  "Cries and Whispers",
  "Fanny and Alexander",
  "Saraband",
  "Through a Glass Darkly",
  "Winter Light",
  "The Silence",
  "Shame",
  "Hour of the Wolf",
  "Persona",
  "Smiles of a Summer Night",
  "The Virgin Spring",
  "Brink of Life",
  "Wild Strawberries",
  "Summer Interlude",
  "Summer with Monika",
  // 201-250
  "A Pigeon Sat on a Branch Reflecting on Existence",
  "You, the Living",
  "Songs from the Second Floor",
  "Roy Andersson Trilogy",
  "The Great Beauty",
  "Il Capitale Umano",
  "The Consequences of Love",
  "Il Divo",
  "Gomorrah",
  "The Hand of God",
  "Umberto D.",
  "La Terra Trema",
  "Bellissima",
  "Rocco and His Brothers",
  "The Conformist",
  "Amarcord",
  "Casanova",
  "And the Ship Sails On",
  "The Sheltering Sky",
  "Last Tango in Paris",
  "1900",
  "The Spider's Stratagem",
  "The Passenger",
  "Blow-Up",
  "L'Avventura",
  "Red Desert",
  "Il Deserto Rosso",
  "Chronicle of a Love",
  "Story of a Love Affair",
  "Le Amiche",
  "Il Grido",
  "La Notte",
  "Portrait of a Lady on Fire",
  "Tomboy",
  "Water Lilies",
  "Girlhood",
  "Things to Come",
  "Goodbye First Love",
  "One Fine Morning",
  "Father of My Children",
  "The Wonders",
  "Happy as Lazzaro",
  "La Chimera",
  "Exhibition",
  "Unrelated",
  "Archipelago",
  "The Souvenir",
  "The Souvenir: Part II",
  "Eternal Daughter",
  "Certain Women",
  "First Cow",
  // 251-300
  "Meek's Cutoff",
  "Wendy and Lucy",
  "Old Joy",
  "River of Grass",
  "Stranger Than Paradise",
  "Down by Law",
  "Mystery Train",
  "Night on Earth",
  "Dead Man",
  "Ghost Dog: The Way of the Samurai",
  "Paterson",
  "Only Lovers Left Alive",
  "Frances Ha",
  "Marriage Story",
  "The Squid and the Whale",
  "Lady Bird",
  "Little Women",
  "20th Century Women",
  "Passing",
  "Moonlight",
  "If Beale Street Could Talk",
  "Medicine for Melancholy",
  "Leave No Trace",
  "Hell or High Water",
  "Winter's Bone",
  "Killer of Sheep",
  "Daughters of the Dust",
  "Losing Ground",
  "Bush Mama",
  "Tongues Untied",
  "Paris Is Burning",
  "The Watermelon Woman",
  "Desert Hearts",
  "The Kids Are All Right",
  "Boys Don't Cry",
  "Brokeback Mountain",
  "Carol",
  "The Hours",
  "Bound",
  "Go Fish",
  "Pariah",
  "Tangerine",
  "Moonrise Kingdom",
  "The Royal Tenenbaums",
  "Rushmore",
  "The Life Aquatic with Steve Zissou",
  "Bottle Rocket",
  "Isle of Dogs",
  "The Grand Budapest Hotel",
  "Asteroid City",
  // 301-350
  "Phantom Thread",
  "There Will Be Blood",
  "Inherent Vice",
  "The Master",
  "Punch-Drunk Love",
  "Magnolia",
  "Hard Eight",
  "Boogie Nights",
  "Uncut Gems",
  "Good Time",
  "Heaven Knows What",
  "Frownland",
  "My Entire High School Sinking into the Sea",
  "Synecdoche, New York",
  "Eternal Sunshine of the Spotless Mind",
  "Adaptation",
  "Being John Malkovich",
  "The Truman Show",
  "Pulp Fiction",
  "Jackie Brown",
  "Kill Bill: Volume 1",
  "Kill Bill: Volume 2",
  "Reservoir Dogs",
  "Once Upon a Time in Hollywood",
  "The Hateful Eight",
  "Django Unchained",
  "Inglourious Basterds",
  "Shutter Island",
  "The Departed",
  "Goodfellas",
  "Raging Bull",
  "Taxi Driver",
  "Mean Streets",
  "Who's That Knocking at My Door",
  "Bringing Out the Dead",
  "The Aviator",
  "The Age of Innocence",
  "Cape Fear",
  "After Hours",
  "The King of Comedy",
  "New York, New York",
  "Alice Doesn't Live Here Anymore",
  "Boxcar Bertha",
  "Silence",
  "Kundun",
  "Gangs of New York",
  "Hugo",
  "The Irishman",
  "Killers of the Flower Moon",
  "Casino",
  // 351-400
  "Heat",
  "Collateral",
  "Ali",
  "The Insider",
  "The Last of the Mohicans",
  "Thief",
  "Manhunter",
  "Miami Vice",
  "Blackhat",
  "Ferrari",
  "Eyes Wide Shut",
  "Full Metal Jacket",
  "The Shining",
  "A Clockwork Orange",
  "Dr. Strangelove",
  "Spartacus",
  "Paths of Glory",
  "Lolita",
  "Barry Lyndon",
  "The Killing",
  "Killer's Kiss",
  "Fear and Desire",
  "Mulholland Falls",
  "Lost Highway",
  "Blue Velvet",
  "Eraserhead",
  "Wild at Heart",
  "The Elephant Man",
  "Twin Peaks: Fire Walk with Me",
  "Inland Empire",
  "Dune",
  "The Straight Story",
  "Seven",
  "Zodiac",
  "Fincher",
  "Fight Club",
  "The Girl with the Dragon Tattoo",
  "Gone Girl",
  "The Social Network",
  "Mank",
  "The Games",
  "Minari",
  "Nomadland",
  "The Rider",
  "American Honey",
  "Fish Tank",
  "Red Road",
  "Ratcatcher",
  "Morvern Callar",
  "We Need to Talk About Kevin",
  // 401-450
  "Under the Skin",
  "Jackie",
  "Spencer",
  "Pablo Larraín films",
  "No",
  "Neruda",
  "El Club",
  "Tony Manero",
  "Post Mortem",
  "Trap",
  "The Zone of Interest",
  "Son of Saul",
  "Ida",
  "Cold War",
  "Pawel Pawlikowski",
  "Shoah",
  "Night and Fog",
  "Hiroshima Mon Amour",
  "Last Year at Marienbad",
  "Muriel, or the Time of Return",
  "La Guerre Est Finie",
  "Mon Oncle d'Amérique",
  "Providence",
  "Stavisky",
  "Wild Grass",
  "My Sex Life... or How I Got into an Argument",
  "Esther Kahn",
  "Kings and Queen",
  "A Christmas Tale",
  "Jimmy P.",
  "My Golden Days",
  "Late August, Early September",
  "Time Out",
  "The Sentinels",
  "Savage Nights",
  "Le Petit Soldat",
  "A Woman Is a Woman",
  "Vivre Sa Vie",
  "My Life to Live",
  "The Little Soldier",
  "Made in USA",
  "One Plus One",
  "First Name: Carmen",
  "Hail Mary",
  "For Ever Mozart",
  "In Praise of Love",
  "Film Socialisme",
  "Goodbye to Language",
  "The Image Book",
  "Pierrot le Fou",
  // 451-500
  "Tropical Malady",
  "Apichatpong Weerasethakul films",
  "Mubi collection",
  "The Assassin",
  "Three Times",
  "Millennium Mambo",
  "Flight of the Red Balloon",
  "What Time Is It There?",
  "The Hole",
  "Rebels of the Neon God",
  "Goodbye, Dragon Inn",
  "The River",
  "Vive l'Amour",
  "I Don't Want to Sleep Alone",
  "Stray Dogs",
  "Visage",
  "Yue Moon",
  "Goodbye South, Goodbye",
  "Dust in the Wind",
  "Good Men, Good Women",
  "City of Sadness",
  "The Boys from Fengkuei",
  "Growing Up",
  "Ah Fei",
  "Summer at Grandpa's",
  "The Sandwich Man",
  "The Green Ray",
  "My Night at Maud's",
  "Claire's Knee",
  "Love in the Afternoon",
  "The Aviator's Wife",
  "Pauline at the Beach",
  "Full Moon in Paris",
  "A Tale of Springtime",
  "A Tale of Winter",
  "A Summer's Tale",
  "An Autumn Tale",
  "Rendez-vous in Paris",
  "The Lady and the Duke",
  "Perceval le Gallois",
  "The Marquise of O",
  "Bérénice",
  "La Femme de l'aviateur",
  "Boyfriends and Girlfriends",
  "Four Adventures of Reinette and Mirabelle",
  "Pauline at the Beach",
  "Conte de Noël",
  "Wild Grass",
  "How I Got into an Argument",
  "Late August, Early September",
];
